tunnel: cgm-butler
credentials-file: /path/to/.cloudflared/credentials.json

ingress:
  # Flask 仪表板
  - hostname: cgm-butler-dashboard.pages.dev
    service: http://localhost:5000
    
  # React 视频数字人
  - hostname: cgm-butler-avatar.pages.dev
    service: http://localhost:5173
  
  # 默认响应
  - service: http_status:404

